# This configuration file defines the generic rules for analyzing the
# logs. This should help with identifying the common problems
# and suggest the solution.
#
# Each rule defines these keys:
#  "desc"   - a short description displayed in the summary
#  "match"  - a Ruby regular expression applied on the
#  "action" - suggested action to resolve the problem

- desc: RPM package build failed
  match: ^\\[\\s*[0-9]+s\\] .* failed "build .*\\.spec" at
  action: Fix the package build

- desc: RPM package build failed
  match: RPM build errors
  action: Fix the package build

- desc: The RSpec unit test failed
  # non-zero number of failures
  match: ^\d+ examples, [1-9]+[0-9]* failure
  action: Fix the RSpec unit test

- desc: Compilation failed
  match: compilation terminated
  action: Fix the package build

- desc: Not packaged directory
  match: ".rpm: directories not owned by a package:$"
  action: Fix the RPM *.spec file

- desc: RPM file conflict
  match: file .* conflicts between attempted installs of .* and .*
  action: Check the package dependencies and the content of the packages

- desc: HTTP service error
  match: "Server returned an error: HTTP Error"
  action: Try restating the build later

- desc: Compiler crashed
  match: "internal compiler error: Segmentation fault"
  action: Hopefully a random issue, try restating the build...
