# This configuration file defines the specific rules for analyzing
# the Jenkins logs.
#
# See more details in the generic_rules.yml file.

- desc: Changes file check failed, missing Bugzilla or Fate ID
  match: "^Stopping, missing new bugzilla or fate entry"
  action: Add bugzilla/fate number to the *.changes file

- desc: 'OBS "service in progress" error'
  match: "^Server returned an error: HTTP Error 400: service in progress$"
  action: Restart the job and submit the package manually

- desc: RPM dependency problem
  match: "^unresolvable: nothing provides"
  action: Check the package dependencies, check the dependant package build status

- desc: The worker run out of the disk space 
  match: No space left on device
  action: Try restarting the build, if that does not help report the issue to the OBS team.

- desc: Missing Rakefile, job cannot be started
  match: ^No Rakefile found
  action: Add Rakefile or reconfigure the Jenkins job to use another tool

- desc: OBS project or package was not found
  match: ^Error getting meta for project
  action: Check the target OBS project, create the package if it is missing

- desc: Broken build root at the Jenkins worker node
  match: Your build system is broken!!
  action: Remove the broken /var/tmp/build-root directory at the Jenkins node
    and then restart the build. Or simply restart the build, maybe it has been
    fixed meanwhile...
